services:
  app:
    build: .
    ports:
      - "4200:4200"
    # volumes:
    #   - ".:/app"
    #   - "/app/node_modules"
    restart: always
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
